### PR TITLE
Agent removed. Deps on JToken removed.

### PR DESCRIPTION
**Pull request by kunjee17**
@Dzoukr hey can you please check if Newtonsoft.Json can be updated to latest. Currently Tests are locked on version 11, I guess because of CosmoStore. 

Not that is conflicting with Marten as it has pushed the deps.

### CODE REVIEW

**Comment by Dzoukr** [comment]
I think you can update deps for Test project with no problem (should not break anything) so keep free to update as needed.

**Comment by Dzoukr** [comment]
Looking at diff - are there really changes in CosmoStore validation or is it just formatting?

**Comment by kunjee17** [comment]
@Dzoukr Just formatting. I was trying to generalize it. But then didn't did it.

**Comment by Dzoukr** [comment]
So this one can be closed since #14 is merged, right?

**Comment by kunjee17** [comment]
Yes. It can be closed.

**Comment by kunjee17** [comment]
There is only one minor change. Removed unused open. You can merge it or close it whatever you like. 

@Dzoukr

**Pull request closed without merging**
