### PR TITLE
Lite DB for cosmo store.

### PR DESCRIPTION
**Pull request by kunjee17**
Hi @Dzoukr 

Here is LiteDB cosmostore implementation. I was able to pass all tests but not without modifying `JToken -> Obj`. Again I don't know if all data is coming back is same as it should. 

I keeping it in PR, and will see what we can do. 

> We gonna meet at FSharpex. May be we can do pair coding there. Even another Roman will be there as well, and confidently he also like ES. :)

### CODE REVIEW

**Comment by Dzoukr** [comment]
Hi @kunjee17,

thanks a lot! I'll pull it and have a look.

**Comment by Dzoukr** [comment]
Hey @kunjee17 I was thinking... what if I create special branch only for this feature (`feature/lite-db`) where we can both contribute and work on LiteDB be ready (+ we will keep master clean) and then you will create PR in master? I'd like to help (and I am glad for your work 🙏) but don't want to merge breaking changes in `JToken -> obj` so we could do it there for now?

Please, let me know.

**Comment by kunjee17** [comment]
@Dzoukr oh not an issue. I just merge branch so you can have a look. I am open for your option. 

It is just that I don't want to take the credit of your hard work (wonderful abstracted library and test cases) so I sent a merge request.

I also had two version of it (one with generic and one with obj ).  

Just keep the WIP for now. I ll keep that in one way sync (master to this branch) for now. And will see what can be done later.

**Comment by Dzoukr** [comment]
No problem. I don't see it as any attempt to take my credit. I see it as you want to help to contribute and I am truly grateful for that! 🙏 I am looking forward to release LiteDB support as soon as it is ready with all the credits for your hard work, my friend.
So lets work together to make it work, test, release, announce and celebrate on FSharpX! 😂

**Comment by Dzoukr** [comment]
Hi mate, please let me know whenever you feel I can merge your PR for LiteDB. I am checking regularly, but not daily so can easily miss it. :)

**Comment by kunjee17** [comment]
@Dzoukr I  ll update this with latest one soon. Sorry couldn't give time due to some medical conditions.

**Comment by Dzoukr** [comment]
No problem at all, mate! No worries, first thing first. Just wanted you know that I am not ignoring it, just need some final ping back from you, that's all. Get well soon!

**Comment by kunjee17** [comment]
@Dzoukr finally LiteDB support is landed. It is good to go. If you merge this PR then #33 will be merged automatically. It is already included.

**Comment by kunjee17** [comment]
I guess we can remove JToken from test. As we are passing them as parameter. But haven't look into it in details. BTW few more support is coming soon.

**Comment by Dzoukr** [comment]
Thanks mate!!! Going to check it and release soon! Thanks again!!!!

**Pull request merged**
